# Generated by Django 5.0.7 on 2024-07-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('quality', models.CharField(max_length=50)),
                ('product_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver')], max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacture_date', models.DateField()),
                ('available', models.BooleanField(default=True)),
                ('rating', models.IntegerField(default=1)),
            ],
        ),
    ]
